#!/bin/sh

# Get the changed files
###########################
ESLINT="./backend/node_modules/.bin/eslint --ext .ts,.js,.jsx "

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '^.*src\/.*\.(js|jsx|tsx|ts)$')

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

$ESLINT "${STAGED_FILES[@]}"

ESLINT_EXIT="$?"

if [[ "${ESLINT_EXIT}" == 0 ]]; then
  printf "\n\033[42mCOMMIT SUCCEEDED\033[0m\n"
else
  printf "\n\033[41mCOMMIT FAILED:\033[0m Fix eslint errors and try again\n"
  exit 1
fi

exit $?