FROM mysql:8.0.32

EXPOSE 3306

#docker build -t rf_mysql . // Run inside the folder in which Dockerfile is present
# docker images // check containers
#docker run --name=rf_mysql -e MYSQL_ROOT_PASSWORD=rf123 -p 3307:3306 -d rf_mysql:latest
# docker ps -a // check container running
#docker exec -it [containerId] /bin/bash

# time DOCKER_BUILDKIT=1 docker buildx build --platform linux/amd64,linux/arm64 -t 574309367192.dkr.ecr.us-west-2.amazonaws.com/rfng-mysql . --push
# time DOCKER_BUILDKIT=1 docker buildx build --platform linux/amd64,linux/arm64 -t prasanti85/rfng-mysql . --push
