# MySql Configuration

apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: kubernetes.io/basic-auth
stringData:
  root_password: password
  database: devrfng
  user: user
  password: password

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/mysql"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rfng-mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rfng-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rfng-mysql
    spec:
      containers:
      - name: rfng-mysql
        image: 574309367192.dkr.ecr.us-west-2.amazonaws.com/rfng-mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: root_password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: database
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        ports:
        - containerPort: 3306
          name: rfng-mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim

---
apiVersion: v1
kind: Service
metadata:
  name: rfng-mysql-service
spec:
  selector:
    app: rfng-mysql
  type: ClusterIP
  ports:
  - port: 3306
    name: mysqldb
    protocol: TCP

---

# MongoDB Configuration

apiVersion: v1
kind: Pod
metadata:
  name: rfng-mongodb
  labels:
    app: rfng-mongodb
spec:
  containers:
    - name: rfng-mongodb
      image: 574309367192.dkr.ecr.us-west-2.amazonaws.com/rfng-mongo:latest
      ports:
        - containerPort: 27017
          name: mongodb-port
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb
  name: rfng-mongodb-service
spec:
  selector:
    app: rfng-mongodb
  type: ClusterIP
  ports:
    - port: 27017
      protocol: TCP
      name: mongodb

---
# Backend Configuration

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rfng-backend-deployment
  labels:
    app: rfng-backend  
spec:
  selector:
    matchLabels:
      app: rfng-backend
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      name: rfng-backend
      labels:
        app: rfng-backend
    spec:
      containers:
      - name: rfng-backend
        image: {{BACKEND_IMAGE}}
        # image: 574309367192.dkr.ecr.us-west-2.amazonaws.com/rfng-backend
        imagePullPolicy: Always
        resources:
          limits:
            memory: "129Mi"
            cpu: "500m"
        ports:
        - containerPort: 4000
          name: nodejs-port


---

apiVersion: v1
kind: Service
metadata:
  name: rfng-backend-service
spec:
  # type: NodePort
  selector:
    app: rfng-backend
  ports:
    - port: 80
      protocol: TCP
      targetPort: 4000
  type: LoadBalancer

---

# Frontend Configuration

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rfng-frontend-deployment
  labels:
    app: rfng-frontend  
spec:
  selector:
    matchLabels:
      app: rfng-frontend
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      name: rfng-frontend
      labels:
        app: rfng-frontend
    spec:
      containers:
      - name: rfng-frontend
        image: {{FRONTEND_IMAGE}}
        # image: 574309367192.dkr.ecr.us-west-2.amazonaws.com/rfng-frontend
        imagePullPolicy: Always
        resources:
          limits:
            memory: 200Mi
            cpu: 100m
        ports:
        - containerPort: 80
          name: http-port
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: rfng-frontend-service
spec:
  selector:
    app: rfng-frontend
  ports:
    - port: 80
      protocol: TCP
      targetPort: http-port
      # nodePort: 30008
  type: LoadBalancer

---

# aws eks --region us-west-1 update-kubeconfig --name eks-cluster-demo

# kubectl create -f kubernetes/web-eks.yaml
# kubectl apply -f=kubernetes/web-eks.yaml
# kubectl get deployments && kubectl get pods && kubectl get namespaces && kubectl get services 
# kubectl exec rfng-backend-deployment-f65f989-8lzg8 -it -- /bin/sh
# kubectl logs rfng-mysql-deployment-cc7dc67f5-4pvmn --all-containers  
# kubectl delete -f=kubernetes/web-eks.yaml

